database:
  type: sqlite
  dsn: "file:proxies.db?cache=shared&mode=rwc"
  max_connections: 10
  retention_days: 30
  metrics_enabled: true
  conn_timeout: 1m
  query_timeout: 30s

proxy:
  rotation_strategy: round-robin
  validate_on_start: true
  refresh_interval: 1h
  max_retries: 3
  timeout: 10s

captcha:
  2captcha_api_key: ${TWOCAPTCHA_API_KEY}
  timeout: 2m
  debug: false
